version: '3.8'

services:
  elasticsearch:
    image: elasticsearch:9.1.2
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - es_data:/usr/share/elasticsearch/data
      - ./elasticsearch/logs:/usr/share/elasticsearch/logs
    mem_limit: 4g
    restart: unless-stopped
    networks:
      - search-network

  qdrant:
    image: qdrant/qdrant
    container_name: qdrant
    environment:
      - LOG_LEVEL=INFO
    ports:
      - "6333:6333" # REST API
      - "6334:6334" # gRPC (optional)
    volumes:
      - ./qdrant_storage:/qdrant/storage:z
    mem_limit: 2g
    restart: unless-stopped
    networks:
      - search-network

# Volumes
volumes:
  es_data:

    # Networks
networks:
  search-network:
    driver: bridge
